### ISSUE TITLE
nginx.ng appears to use ppa only in debian?

### ISSUE THREAD

**Issue by froztbyte** [saltstack-formulas/nginx-formula#100]
What's the rationale in referencing only against a PPA for installing nginx?

Would a PR for enabling stable/backports/dotdeb be accepted?

**Comment by froztbyte** [comment]
I found this now:

```
nginx_install:
  {% if nginx.install_from_source %}
  ## add source compilation here
  {% else %}
  pkg.installed:
    {{ sls_block(nginx.package.opts) }}
    - name: {{ nginx.lookup.package }}
  {% endif %}

{% if salt['grains.get']('os_family') == 'Debian' %}
nginx_ppa_repo:
  pkgrepo:
    {%- if nginx.install_from_ppa %}
    - managed
    {%- else %}
    - absent
    {%- endif %}
    - ppa: nginx/{{ nginx.ppa_version }}
    - require_in:
      - pkg: nginx_install
    - watch_in:
      - pkg: nginx_install
{% endif %}
```

So it seems that it does a `watch_in` to enforce the PPA and otherwise default to distro. I could add `backports` to this?

**Comment by gravyboat** [comment]
That's specifically for the ng formula, if you want to add additional functionality feel free to prep a PR for review!

**Comment by arthurlogilab** [comment]
It would indeed be useful to have a dotdeb option too

**Comment by noelmcloughlin** [comment]
> if you want to add additional functionality feel free to prep a PR for review!
