### ISSUE TITLE
Managed SSL Certificates owned by root

### ISSUE THREAD

**Issue by SunPowered** [saltstack-formulas/nginx-formula#106]
The `nginx.ng.certificates` state forces all managed certificates to be owned by root.  This causes issues when the nginx server is being run by users other than root as the SSL key has permissions 600.  

Ideally the certificates should be owned by user and group of the default nginx user (ie `www-data`), taken from the map file, `nginx:ng:webuser`.

**Comment by EvaSDK** [comment]
I run this formula under Debian, which has this kind of setup and it does not cause any problem as the master nginx process is started as root. Could you be more specific about your problem, what is your distribution, etc ?

**Comment by noelmcloughlin** [comment]
The view on the internet is that this file must be owned by root and 0600 and nginx should be started as root user (both apache and nginx will spawn non-root processes).

https://github.com/chef/chef-server/issues/731
https://httpd.apache.org/docs/2.4/ssl/ssl_faq.html#removepassphrase
