### ISSUE TITLE
support for dhparam files

### ISSUE THREAD

**Issue by roock** [saltstack-formulas/nginx-formula#116]
For high grade security site you should supply a custom dhparam file per domain/certificate. I've started working on this issue, but it needs some more work to skip the file if it is not present in the pillar data.

https://github.com/roock/nginx-formula/commit/c44787771e19ddae64697b8faf687eea8af0d990

**Comment by EvaSDK** [comment]
See PR #129

**Comment by EvaSDK** [comment]
@aboe76, I guess this issue is resolved since PR #153 was merged.

**Comment by aboe76** [comment]
@EvaSDK yes closing this report.
