### ISSUE TITLE
Overriding values in nginx.ng is pretty tricky.

### ISSUE THREAD

**Issue by nicksloan** [saltstack-formulas/nginx-formula#132]
The biggest problem that I have with this formula is in overriding values. Different minions have different server_name directives, for example. Given the list structure for most directives, I can't rely on dictionary merging to allow me to supply additional bits of config in other files.

I am wondering what approach the authors of this formula have arrived at to minimize repetition while still allowing different minions to be targeted with different values at the vhost level. I'd be happy to compile the output of this discussion into additional examples in the pillar.example file.

**Comment by rtaft** [comment]
Same here.  I was able to override the certificates, but not the name of the cert files.  It's much easier to do this manually when you have multiple configs to manage where only one or two things change between the configs.

**Comment by EvaSDK** [comment]
I have written some macros for most used patterns in my `nginx.ng` servers definitions.
Other directives could not really be factored anyway so I feel this is a decent solution preserving readability and flexibility.

**Comment by noelmcloughlin** [comment]
Resolved in #165
