### ISSUE TITLE
Specified path /etc/nginx/.htpasswd does not exist

### ISSUE THREAD

**Issue by marek-knappe** [saltstack-formulas/nginx-formula#139]
Have nothing about .htpasswd in my pillars

```
----------
          ID: htpasswd
    Function: pkg.installed
        Name: apache2-utils
      Result: True
     Comment: Package apache2-utils is already installed
     Started: 23:45:11.566766
    Duration: 0.396 ms
     Changes:
----------
          ID: make sure /etc/nginx/.htpasswd exists
    Function: file.exists
        Name: /etc/nginx/.htpasswd
      Result: False
     Comment: Specified path /etc/nginx/.htpasswd does not exist
     Started: 23:45:11.567240
    Duration: 0.342 ms
     Changes:
```

**Comment by scub** [comment]
The [user states](https://github.com/saltstack-formulas/nginx-formula/blob/master/nginx/users.sls) are [enabled by default](https://github.com/saltstack-formulas/nginx-formula/blob/master/nginx/init.sls#L10-L11) - you will need to override ```user_auth_enabled``` in your ["nginx" Pillar](https://github.com/saltstack-formulas/nginx-formula/blob/master/pillar.example#L5):

```
nginx:
  user_auth_enabled: False
```

**Comment by myoung34** [comment]
Closing as resolved per @scub pointed out
