### ISSUE TITLE
Nginx logger error

### ISSUE THREAD

**Issue by ericuldall** [saltstack-formulas/nginx-formula#143]
I keep getting install errors complaining about nginx-logger-(access|error) missing

Minion logs:
```
2017-01-20 01:08:28,888 [salt.state       ][ERROR   ][6994] The named service nginx-logger-access is not available
2017-01-20 01:08:29,046 [salt.state       ][ERROR   ][6994] The named service nginx-logger-error is not available
```

I'm not sure what these services are and if they are even necessary. Is there any known fix for this error?

Minion version: Linux version 4.4.0-59-generic (buildd@lgw01-11) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017

**Comment by noelmcloughlin** [comment]
See https://github.com/saltstack-formulas/nginx-formula/issues/14 and particularly 
https://github.com/saltstack-formulas/nginx-formula/issues/109

I am also trying to resolve this problem on 16.04

**Comment by noelmcloughlin** [comment]
Systemd support missing - workaround for Ubuntu 16.04

- Set 'use_upstart': False and 'use_sysvinit': False in the map.jinja' file

- Update users.sls and touc the .htpasswd file if missing-
`make sure {{ htauth }} exists:
    file.touch:
    - name:  {{ htauth }}
    - onlyif: [ ! -e {{ htauth }} ]`

**Comment by ninapavlich** [comment]
@noelmcloughlin I'm a little confused by the formatting in your message, any chance you could edit it to be a little more clear? (Which specifically were not working and which you changed?)

**Comment by noelmcloughlin** [comment]
@ninapavlich it got corrupted (deleted now).  I'll check this week but probably solution involves setting both '`use_upstart: True`' and '`use_sysvinit: False`'

**Comment by noelmcloughlin** [comment]
This is not affecting me in Ubuntu 18.04 using `nginx.ng`.  

I'd recommend everyone uses `nginx.ng` instead of `ngninx` state.
