### ISSUE TITLE
file.managed of nginx.conf removes inclusion of .../modules-enabled/*.conf in Nginx 1.10

### ISSUE THREAD

**Issue by joe-bowman** [saltstack-formulas/nginx-formula#151]
The management of the `nginx.conf` removes the line:
```
include /etc/nginx/modules-enabled/*.conf
```
in nginx 1.10 (I suspect, 1.9 onwards, when dynamic modules were added).

Adding this in `nginx.ng.config` doesn't work, as the unordered list causes this to get added too far down the file (it needs to be at the top before other declarations).

**Comment by javierbertoli** [comment]
Should be fixed on #157
