### ISSUE TITLE
`from_official` is undefined

### ISSUE THREAD

**Issue by IvanVergiliev** [saltstack-formulas/nginx-formula#159]
https://github.com/saltstack-formulas/nginx-formula/pull/158 seems to break the formula, resulting in the following message:

```
2017-06-26 14:47:38,429 [salt.state       ][CRITICAL][30899] Rendering SLS 'base:nginx.ng.pkg' failed: Jinja variable 'from_official' is undefined
```

**Comment by aboe76** [comment]
@javierbertoli can you take a look?

**Comment by javierbertoli** [comment]
Sure. On it.

**Comment by javierbertoli** [comment]
@aboe76, @IvanVergiliev, please check #160

**Comment by aboe76** [comment]
@IvanVergiliev and @javierbertoli merged

**Comment by IvanVergiliev** [comment]
Thanks for the quick fix!
