### ISSUE TITLE
1st time install - Update pillar.example / README warning about port 80

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/nginx-formula#169]
Nginx has poor packaging design. They abort the package manager subprocess if port 80 is already bound.  No package should abort package install like this (warning would suffice)  - but they do - so OS package manager is left in a mess.  Log attached for Ubuntu.

[salt-formula-faillure-port-80.txt](https://github.com/saltstack-formulas/nginx-formula/files/1270630/salt-formula-faillure-port-80.txt)

We should consider updating README and/or pillar.example with warning. It looks like fault of salt-formula problem but its not.

**Comment by noelmcloughlin** [comment]
Secondly, need to check if this could be detected/handled in formula and fixed  (sudo apt-get -f install) but I don't think so - unless there is a fix-os-package-manager-state formula?

**Comment by dseira** [comment]
We can add some warning message in the README but do something inside the formula to try to fix I think it wouldn't be the proper solution. Anyway let me think about it.

**Comment by johnkeates** [comment]
We should report this as a bug to the package maintainer, but put a note in this formula indeed.

**Comment by noelmcloughlin** [comment]
Thanks @dseira @johnkeates  nginx upstream are standing firm saying its environment issue despite lots of user-land issues. I added a comment while back pushing for fix.

**Comment by arthurlogilab** [comment]
Getting hit by this bug too. 

Am contemplating adding a `require_in` state that checks the port is not bound, so that `dpkg` is not left in an error state (it has impacts on other packages not being installed in our case).

**Comment by noelmcloughlin** [comment]
Hi @arthurlogilab could you look at that PR.  

This seems to be duplicate of #17 so one PR to kill 2 issues is nice :-)
