### ISSUE TITLE
Hangs during nginx package install on Ubuntu 14.04

### ISSUE THREAD

**Issue by audreyr** [saltstack-formulas/nginx-formula#17]
This formula hangs during:

```
[INFO    ] Executing command ['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'nginx'] in directory '/home/vagrant'
```

It happens even with very conservative pillar choices:

```
nginx:
  install_from_source: False
  use_upstart: False
  with_luajit: False
  with_openresty: False
```

I let it go for over 1 hour and it looks like nothing's happening. I think it's a nginx-formula issue because:
- I have this isolated on my system: I am executing just the nginx states from this formula, not highstate.
- I have this set up as a gitfs remote in my master.conf
- My internet connection is strong and hiccup-free.

I'm using a local VM instance, provisioned with Vagrant from this box image: http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box

I am now going through nginx-formula in detail to troubleshoot this. If anyone has suggestions about things to try or possible causes, your feedback would be welcome and very appreciated.

**Comment by bahadir** [comment]
What does strace nginx -t -c /path/to/nginx.conf says? I had a similar problem long time ago. When I strace'd it, log.fifo files were missing.

**Comment by noelmcloughlin** [comment]
Closing this as nginx packaging issue.
> you're hanging on package install and I'm hanging on service nginx start
> It hangs here because the post-install starts the nginx service.

Please join discussion on #169 about how to workaround nginx post-install service starts.
