### ISSUE TITLE
nginx:ng:certificates.sls broken in commit 4204505?

### ISSUE THREAD

**Issue by 9numbernine9** [saltstack-formulas/nginx-formula#174]
Hello!

I think there might be a problem in `certificates.sls` as a result of commit 4204505. Line `8` now says:
```
{%- for dh_param, value in salt.pillar.get('nginx:ng:dh_param').items() %}
```
But this will fail with `Jinja variable 'str object' has no attributes 'items'` if you don't define any `dh_param` in your pillar. I think the right fix for this might be to change the line such that a safe default is provided if `dh_param` isn't specified, e.g.:
```
{%- for dh_param, value in salt['pillar.get']('nginx:ng:dh_param', {}).items() %}
```
With this change, if `dh_param` isn't specified, the dict will be empty and `#items` can be safely invoked on it. 

Thanks!

**Comment by aboe76** [comment]
Would you mind to make a pr?

**Comment by 9numbernine9** [comment]
Done! PR is #175.

**Comment by EvaSDK** [comment]
PR merged, this ticket can be closed now.
