### ISSUE TITLE
Fix needed for Suse

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/nginx-formula#204]
This issue is outstanding from merged #203 PR.

> I see the issue see:
> {% set nginx = pillar.get('nginx', {}) -%}
> 
> this should be:
> {% set nginx = pillar.get('nginx_map', {}) -%}

> why export nginx in map.jinja and then import is as nginx_map...and not use it,
> the set commands all drag settings from pillar under the nginx key...

**Comment by aboe76** [comment]
@noelmcloughlin I don't think this is an issue, at first glance this looks wrong in the code...

```
{% from "nginx/map.jinja" import nginx as nginx_map with context %}
```
import map.jinja nginx as nginx_map will acquire all info from map.jinja 
but map.jinja doesn't pull pillar key nginx.....!!!!
map.jinja only pulls nginx:lookup...

so add nginx to pull pillar nginx key here isn't wrong.
```
{% set nginx = pillar.get('nginx', {}) -%}
```
and if home isn't set in pillar nginx key it will look it up in the nginx_map which is the correct way.
```
{% set home = nginx.get('home', nginx_map.home) -%}
```

**Comment by noelmcloughlin** [comment]
Thanks for checking this @aboe76
