### ISSUE TITLE
BREAKING CHANGE: Replace old `nginx` with `nginx.ng` (v1.0.0)

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/nginx-formula#230]
The introduction of `semantic-release` in #229 paves the way for this formula to remove the old `nginx` configuration and to replace it with `nginx.ng`.

**Comment by myii** [comment]
@daks @noelmcloughlin @aboe76 Apologies, got mixed up with a PR and starting setting the assignees thinking it was reviewers!  What I meant to do was simply ping each of you for the discussion.

**Comment by daks** [comment]
I'm totally in favour of this change!

**Comment by noelmcloughlin** [comment]
I second that @daks
A non-breaking approach is to update the README to remove all references to `ng`, wipe all `nginx` SLS codee, and replace with `include nginx.ng.xxx` from `nginx.xxx` - non breaking impact.  I'm not advocating this but noting the approach.

**Comment by johnkeates** [comment]
I am SO GLAD this is finally happening!

**Comment by myii** [comment]
@daks bit the bullet and delivered in #232!  It's merged now so start modifying your configs!
