### ISSUE TITLE
[BUG] events / worker_connections set to 768 in default configuration 

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/nginx-formula#261]
### Describe the bug

After upgrading to a new formula 
```
                  +events {
                  +    worker_connections 768;
                  +}
```

https://nginx.org/en/docs/ngx_core_module.html#worker_connections seems to indicate a default of 512, what is the rational for this different default here ?

**Comment by myii** [comment]
Looking through the history, that was introduced by @daks in [`0fc5070`](https://github.com/saltstack-formulas/nginx-formula/commit/0fc507055df7fa62db83bcc31aabebecb96c87d2#diff-98eac190e72f39f84b8ec9c2311d0d69R132-R134) (#232); perhaps he has more information about it.  Also relevant to this discussion:

* https://github.com/saltstack-formulas/nginx-formula/pull/217#discussion_r274122629
* https://freenode.logbot.info/saltstack-formulas/20190410#c2108019

**Comment by daks** [comment]
Not sure why I added this setting, maybe just because tests didn't pass without it. May be worth to try without.

**Comment by myii** [comment]
@daks Thanks, we'll modify the default to be `512`, then.

**Comment by myii** [comment]
@arthurlogilab @daks I've prepared #262 to deal with this.
