### ISSUE TITLE
Test config before reload service

### ISSUE THREAD

**Issue by minch4** [saltstack-formulas/nginx-formula#272]
Hello :wave: 

Is that possible to add a config test (something like `nginx -t`) condition for reloading the service ?

Thank you very much :smile:

**Comment by javierbertoli** [comment]
@minch4, this feature was added in 622d22f9 as part of #278

Check [the pillar.example](https://github.com/saltstack-formulas/nginx-formula/blob/master/pillar.example#L31-L40) for usage and caveats.
