### ISSUE TITLE
[BUG] How to set internal property on pillar?

### ISSUE THREAD

**Issue by thomasrossetto** [saltstack-formulas/nginx-formula#279]
Hi, I want to use Internal declaration (http://nginx.org/en/docs/http/ngx_http_core_module.html#internal) into my nginx configuration pillar, but I don't know how to write it.

Do you have some ideas?

Thanks!

**Comment by myii** [comment]
@thomasrossetto One definite suggestion would be to use TOFS, which has has been enabled for this formula as well in #238.  Or the simpler method of using [`source_path`](https://github.com/saltstack-formulas/nginx-formula/blob/1d9a15fe49c5456a7552dd797c49afabcabfa294/pillar.example#L122-L125) is still available.  There might be a way of defining directly in pillar but I haven't tried doing that -- the general move has been towards allowing end users to provide their own custom templates instead (i.e. TOFS or `source_path` mentioned above).

**Comment by javierbertoli** [comment]
@thomasrossetto sorry if I got late to help. If you already solved it, I'll leave this example here for future reference.

This
```yaml
mysite.conf:
  enabled: true
  config:
    - server:
        - server_name: my-site
        ...
        ...
        - location = /404.html:
            - internal: ''
}
```
will add a section like the one you're linking to.

The rationale the configuration template macro follows is:
* if the *value* for a *key* is a _list_, it will start a new `{}` section, so
```yaml
- location = /404.html:
    - ...
```
gives you
```json
location = /404.html {
...
}
...
```
* if the *value* for a *key*  is a _string_ or a _number_, it will be converted into a line in the configuration:
```yaml
- server_name: localhost
```
gives you
```
server_name localhost;
```

For your particular request, making the *value* assignment an empty string gives you the result you expect.
