### ISSUE TITLE
wrong sites-enabled inclusion pattern

### ISSUE THREAD

**Issue by teepark** [saltstack-formulas/nginx-formula#48]
the nginx.conf that comes in the debian/ubuntu package includes `sites-enabled/*` and `conf.d/*.conf`, while the one in this formula requires a .conf extension on sites-enabled, meaning even the package-distributed "default" symlink doesn't get included and it 404s on everything until a site is explicitly created.

if we don't want the default one included that's fine, but let's do it properly and `file.absent` out `sites-enabled/default` rather than having it _accidentally_ skipped.

**Comment by edvinasme** [comment]
An option to prune any non-salt managed configuration files might be a good idea also.

**Comment by noelmcloughlin** [comment]
The filename `/etc/nginx/sites-enabled/default` should indeed be included.  This issue is fixed in current code - just tested today and my site in **default** is started by nginx daemon.
```
# tail /etc/nginx/nginx.conf 
    tcp_nopush on;
    types_hash_max_size 2048;

    include mime.types;
    include conf.d/*.conf;
    include sites-enabled/*;
}
pid /run/nginx.pid;
user www-data;
worker_processes 4;

# ls -l /etc/nginx/sites-enabled/
total 0
lrwxrwxrwx 1 root root 34 Jan 25 07:51 default -> /etc/nginx/sites-available/default
```
