### ISSUE TITLE
Pid path broken on RedHat again

### ISSUE THREAD

**Issue by stromnet** [saltstack-formulas/nginx-formula#96]
da1405c5e765b17701ec54182c2bbfd123b32655 (nginx/ng/map.jinja) broke the pid_file fix merged in #86

**Comment by stromnet** [comment]
Actually, on EL7 it seems /run is used. But on EL6, it would be /var/run.

**Comment by alinefr** [comment]
RH 7 uses /run.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Migration_Planning_Guide/sect-Red_Hat_Enterprise_Linux-Migration_Planning_Guide-File_System_Layout.html

For RH 6 you could set pid_path in pillar.
``
nginx:
  pid_path: /var/run/nginx.pid
``

**Comment by noelmcloughlin** [comment]
Thanks @alinefr and @stromnet    This is fully documented in pillar.example now
